"""add user foreign key to pitch dt

Revision ID: fbf816874226
Revises: 1188545c9b73
Create Date: 2022-03-07 13:23:56.948122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbf816874226'
down_revision = '1188545c9b73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pitch', 'users', ['user_id'], ['id'])
    op.drop_constraint('users_pitch_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'pitch_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pitch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_pitch_id_fkey', 'users', 'pitch', ['pitch_id'], ['id'])
    op.drop_constraint(None, 'pitch', type_='foreignkey')
    op.drop_column('pitch', 'user_id')
    # ### end Alembic commands ###
